const DEFAULT_PADDLE_SPEED := 500

const BALL_START_SPEED := 300.0
const BALL_ACCELERATION := 50

const COLLISION_PLAYER := 1
const COLLISION_WALL := 2
const COLLISION_BALL := 3

const MAX_Y_VECTOR: float = 0.6